name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # ou qualquer branch que você queira disparar
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up QEMU (para multiarch se quiser futuramente)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile   # caminho do seu Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dia:latest
